<?php

namespace ContainerLYuOxCw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SfVgTvmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sfVgTvm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sfVgTvm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'flasher' => ['services', 'flasher', 'getFlasherService', false],
            'reclamationResponseRepository' => ['privates', 'App\\Repository\\ReclamationResponseRepository', 'getReclamationResponseRepositoryService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'entityManager' => '?',
            'flasher' => '?',
            'reclamationResponseRepository' => 'App\\Repository\\ReclamationResponseRepository',
            'validator' => '?',
        ]);
    }
}
