<?php

namespace ContainerLYuOxCw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EMQfWloService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eMQfWlo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eMQfWlo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'lineTradeRepository' => ['privates', 'App\\Repository\\LineTradeRepository', 'getLineTradeRepositoryService', true],
        ], [
            'entityManager' => '?',
            'lineTradeRepository' => 'App\\Repository\\LineTradeRepository',
        ]);
    }
}
