<?php

namespace ContainerLYuOxCw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JZM80YZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JZM80YZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JZM80YZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'flasher' => ['services', 'flasher', 'getFlasherService', false],
            'lineTradeRepository' => ['privates', 'App\\Repository\\LineTradeRepository', 'getLineTradeRepositoryService', true],
        ], [
            'flasher' => '?',
            'lineTradeRepository' => 'App\\Repository\\LineTradeRepository',
        ]);
    }
}
