<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adder' => [parent::class, 'adder', null],
        "\0".parent::class."\0".'category' => [parent::class, 'category', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'long_description' => [parent::class, 'long_description', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'short_description' => [parent::class, 'short_description', null],
        "\0".parent::class."\0".'toRequestTreades' => [parent::class, 'toRequestTreades', null],
        "\0".parent::class."\0".'traded' => [parent::class, 'traded', null],
        'adder' => [parent::class, 'adder', null],
        'category' => [parent::class, 'category', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'long_description' => [parent::class, 'long_description', null],
        'name' => [parent::class, 'name', null],
        'short_description' => [parent::class, 'short_description', null],
        'toRequestTreades' => [parent::class, 'toRequestTreades', null],
        'traded' => [parent::class, 'traded', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
