<?php

namespace ContainerDnEHKEU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BQu9D9sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BQu9D9s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BQu9D9s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'flasher' => ['services', 'flasher', 'getFlasherService', false],
            'lineLivraisonRepository' => ['privates', 'App\\Repository\\LineLivraisonRepository', 'getLineLivraisonRepositoryService', true],
        ], [
            'entityManager' => '?',
            'flasher' => '?',
            'lineLivraisonRepository' => 'App\\Repository\\LineLivraisonRepository',
        ]);
    }
}
