<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWz7cxoq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWz7cxoq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWz7cxoq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWz7cxoq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWz7cxoq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wz7cxoq',
    'container.build_id' => '69467c7e',
    'container.build_time' => 1708959106,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWz7cxoq');
