<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLYuOxCw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLYuOxCw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLYuOxCw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLYuOxCw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLYuOxCw\App_KernelDevDebugContainer([
    'container.build_hash' => 'LYuOxCw',
    'container.build_id' => 'e1829e89',
    'container.build_time' => 1709517549,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLYuOxCw');
